### ISSUE TITLE
exposure response

### ISSUE THREAD

**Issue by dingying85** [Novartis/xgx#24]
I could not reproduce the figure in the code on the website
https://opensource.nibr.com/xgx/Multiple_Ascending_Dose_PKPD_binary.html

pkpd_data_wide_plot = pkpd_data_wide %>%
  mutate(PROFDAY_STR = paste("Day",PROFDAY)) %>%
  filter(PROFDAY %in% c(1,3,5)) %>%
  mutate(CONC_QUART = cut(CONC, quantile(CONC, na.rm=TRUE), na.rm=TRUE, include.lowest = TRUE)) %>%
  group_by(CONC_QUART) %>%
  mutate(CONC_MIDPOINT = median(CONC))

gg <- ggplot(data = pkpd_data_wide_plot, aes(x = CONC, y = PD))
gg <- gg + geom_jitter(aes(color = TRTACT_high2low), width = 0, height = 0.05, alpha = 0.5) 
gg <- gg + geom_smooth(method = "glm", method.args = list(family=binomial(link = logit)), color = "black")
gg <- gg + xgx_stat_ci(aes(x = CONC_MIDPOINT, y = PD), distribution = "binomial", geom = "errorbar", size = 0.5)
gg <- gg + xgx_stat_ci(aes(x = CONC_MIDPOINT, y = PD), distribution = "binomial", geom = "point", shape = 0, size = 4)
gg <- gg + scale_y_continuous(labels=scales::percent)
gg <- gg + labs(x = conc_label, y = pd_response_label, color = trtact_label)
gg <- gg + xgx_scale_x_log10()
gg <- gg + facet_grid(~PROFDAY_STR)
print(gg)

After I plot, it miss the error bar and points on the curve, it looks like below:
![image](https://user-images.githubusercontent.com/5166102/88628626-18860f00-d063-11ea-99cd-499aa94191f9.png)

**Comment by iamstein** [comment]
Can you first just look at pkpd_data_wide_plot to make sure it looks reasonable?  You could paste head(pkpd_data_wide_plot) into the reply.  And also can you add geom_point() above to confirm all the points are at the 4 exposure quantiles?  Finally, can you also tell me what version of ggplot2 and xgxr you are using?  At one point, the stat_summary() command changed the way it calculated the confidence intervals (switching from always up-and-down to trying to look at the dataset and "intelligently guess" which direction to draw it in).  That screwed up our command xgx_stat_ci() but there's a fix for that, too.  I just first wanted to understand the issue before telling you to try other things.

**Comment by dingying85** [comment]
Dear Andrew,

Thanks for your reply.

Below is the head(pkpd_data_wide_plot).
ID NOMTIME PD BINARY_LEVELS    TIME TIMEUNIT AMT   CONC CMT
NAME EVENTU CENS EVID
1 11    23.9  0  Nonresponder  23.381    Hours   0 0.0738   2 PK
Concentration  ng/mL    0    0
2 11    71.9  0  Nonresponder  71.310    Hours   0 0.2040   2 PK
Concentration  ng/mL    0    0
3 11   119.9  0  Nonresponder 119.560    Hours   0 0.0958   2 PK
Concentration  ng/mL    0    0
4 12    23.9  0  Nonresponder  23.913    Hours   0 0.0801   2 PK
Concentration  ng/mL    0    0
5 12    71.9  0  Nonresponder  71.714    Hours   0 0.2200   2 PK
Concentration  ng/mL    0    0
6 12   119.9  1     Responder 119.735    Hours   0 0.1020   2 PK
Concentration  ng/mL    0    0
  WEIGHTB  SEX DOSE PROFDAY PROFTIME CYCLE LIDV_NORM LIDV_UNIT DAY_label
TRTACT_low2high
1    90.0 Male  100       1     23.9     1  0.000738     ng/mL     Day 1
       100 mg
2    90.0 Male  100       3     23.9     3  0.002040     ng/mL     Day 3
       100 mg
3    90.0 Male  100       5     23.9     5  0.000958     ng/mL     Day 5
       100 mg
4    69.9 Male  100       1     23.9     1  0.000801     ng/mL     Day 1
       100 mg
5    69.9 Male  100       3     23.9     3  0.002200     ng/mL     Day 3
       100 mg
6    69.9 Male  100       5     23.9     5  0.001020     ng/mL     Day 5
       100 mg
  TRTACT_high2low PROFDAY_STR     CONC_QUART CONC_MIDPOINT
1          100 mg       Day 1 [0.0675,0.293]        0.1705
2          100 mg       Day 3 [0.0675,0.293]        0.1705
3          100 mg       Day 5 [0.0675,0.293]        0.1705
4          100 mg       Day 1 [0.0675,0.293]        0.1705
5          100 mg       Day 3 [0.0675,0.293]        0.1705
6          100 mg       Day 5 [0.0675,0.293]        0.1705

I tried to add the geom_point() and below is the plot
[image: image.png]


Also as you mentioned, it happened to me in another example that confidence
intervals did show up but it is not up and down but shows in horizontal
way.

Also below is the version of the package:
ggplot2: 3.3.0
xgxr:1.0.9.


Best Regards,
Ying Ding




Andrew Stein <notifications@github.com> 于2020年7月28日周二 上午3:23写道：

**Comment by iamstein** [comment]
To fix the problem with the "error bars" going the wrong way, you could either update to ggplot2: 3.3.2 or you could add the following option to the xgx_stat_ci() function
   
   orientation = "x"

Looking at the variable pkpd_data_wide_plot though, something more serious is going wrong.  If you look at the code for it, this data.frame is supposed to have some columns called CONC_QUART and CONC_MIDPOINT, but it does not.  So when you go to plot the quartiles, there's nothing to plot!  I think at this point, the easiest way to debug is if you wanted to have a short 1-1 meeting and I could help you get to the bottom of what's going on and why those columns aren't being created.  For some reason, the newest image you created doesn't appear, but I think looking at the data.frame provides enough info to start debugging.

**Comment by dingying85** [comment]
Thanks Andrew, actually as you suggested, upgrading the ggplot2 solves the
problem. -Ying

Andrew Stein <notifications@github.com> 于2020年7月30日周四 上午4:14写道：

**Comment by iamstein** [comment]
Great!
